NCEPLIBS-bacio: bacio.c File Reference
bacio.c File Reference
Fortran-callable routines to read and write characther (bacio) and numeric (banio) data byte addressably.
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <malloc.h>
#include <ctype.h>
#include <string.h>
#include "clib.h"
Functions
int bacio_ (int *mode, int *start, int *newpos, int *size, int *no, int *nactual, int *fdes, const char *fname, char *datary, int namelen, int datanamelen)
Do bacio operation.
int baciol_ (int *mode, long int *start, long int *newpos, int *size, long int *no, long int *nactual, int *fdes, const char *fname, char *datary, int namelen, int datanamelen)
Do bacio operation, with new names for long int arguments, needed for files > 2 Gb.
int banio_ (int *mode, int *start, int *newpos, int *size, int *no, int *nactual, int *fdes, const char *fname, char *datary, int namelen)
Do banio operation.
int baniol_ (int *mode, long int *start, long int *newpos, int *size, long int *no, long int *nactual, int *fdes, const char *fname, char *datary, int namelen)
Do banio operation, with new names for long int arguments, needed for files > 2 Gb.
Detailed Description
Fortran-callable routines to read and write characther (bacio) and numeric (banio) data byte addressably.
v1.1:
Put diagnostic output under control of define VERBOSE or QUIET
Add option of non-seeking read/write
Return code for fewer data read/written than requested
v1.2:
Add cray compatibility 20 April 1998 Robert Grumbine
v1.3:
Add IBMSP compatibility (IBM4, IBM8)
Add modes BAOPEN_WONLY_TRUNC, BAOPEN_WONLY_APPEND
Use isgraph instead of isalnum + a short list of accepted characters for filename check 12 Dec 2000 Stephen Gilbert
negative return codes are wrapped to positive, revise return codes verify that banio and bacio have same contents, update comments 29 Oct 2008 Robert Grumbine
v1.4:
21 Nov 2008 Add baciol and baniol functions, versions to work with files over 2 Gb Robert Grumbine
Aug 2012 Jun Wang fix c filename length because the c string needs to end with "null" terminator , and free allocated cfile name realname to avoid memory leak.
Sep 2012 Jun Wang: remove execute permission on the data file generated by bacio.
Author
Robert Grumbine
Date
16 March 1998
Definition in file bacio.c.
Function Documentation
bacio_()
int bacio_ (int * mode, int * start, int * newpos, int * size, int * no, int * nactual, int * fdes, const char * fname, char * datary, int namelen, int datanamelen)
Do bacio operation.
Parameters
mode integer specifying operations to be performed see the clib.inc file for the values. Mode is obtained by adding together the values corresponding to the operations The best method is to include the clib.inc file and refer to the names for the operations rather than rely on hard-coded values.
start byte number to start your operation from. 0 is the first byte in the file, not 1.
newpos position in the file after a read or write has been performed. You'll need this if you're doing 'seeking' read/write.
size is the size of the objects you are trying to read. Rely on the values in the locale.inc file. Types are CHARACTER, INTEGER, REAL, COMPLEX. Specify the correct value by using SIZEOF_type, where type is one of these. (After having included the locale.inc file).
no is the number of things to read or write (characters, integers, whatever).
nactual is the number of things actually read or written. Check that you got what you wanted.
fdes is an integer 'file descriptor'. This is not a Fortran Unit Number You can use it, however, to refer to files you've previously opened.
fname is the name of the file. This only needs to be defined when you are opening a file. It must be (on the Fortran side) declared as CHARACTER*N, where N is a length greater than or equal to the length of the file name. CHARACTER*1 fname[80] (for example) will fail.
datary is the name of the entity (variable, vector, array) that you want to write data out from or read it in to. The fact that C is declaring it to be a char * does not affect your fortran.
namelen - Do NOT specify this. It is created automagically by the
Fortran compiler
datanamelen - Do NOT specify this. It is created automagically by the
Fortran compiler
Note
In your Fortran code, call bacio(), not bacio_().
What is going on here is that although the Fortran caller will always be calling bacio, the called C routine name will change from system to system.
Returns
0 All was well
255 Tried to open read only and write only
254 Tried to read and write in the same call
253 Internal failure in name processing
252 Failure in opening file
251 Tried to read on a write-only file
250 Failed in read to find the 'start' location
249 Tried to write to a read only file
248 Failed in write to find the 'start' location
247 Error in close
246 Read or wrote fewer data than requested
102 Massive catastrophe – datary pointer is NULL
Author
Robert Grumbine
Date
16 March 1998
< Read only.
< Write only.
< Write only truncate.
< Write only append.
< Read.
< Write.
< Read only.
< Write only.
< Write only truncate.
< Write only append.
< Read/write.
< Read only.
< Write only.
< Write only truncate.
< Write only append.
< Read/write.
< Read.
< Write only.
< Write only truncate.
< Write only append.
< Read.
< No seek.
< Write.
< Read only.
< Write.
< No seek.
< Close.
< Read only.
< Write only.
< Write only truncate.
< Write only append.
< Read/write.
< Read.
< Write.
Definition at line 132 of file bacio.c.
References bacio_module::bacio, BACLOSE, banio_(), BAOPEN_RONLY, BAOPEN_RW, BAOPEN_WONLY, BAOPEN_WONLY_APPEND, BAOPEN_WONLY_TRUNC, BAREAD, BAWRITE, and NOSEEK.
baciol_()
int baciol_ (int * mode, long int * start, long int * newpos, int * size, long int * no, long int * nactual, int * fdes, const char * fname, char * datary, int namelen, int datanamelen)
Do bacio operation, with new names for long int arguments, needed for files > 2 Gb.
Parameters
mode integer specifying operations to be performed see the clib.inc file for the values. Mode is obtained by adding together the values corresponding to the operations The best method is to include the clib.inc file and refer to the names for the operations rather than rely on hard-coded values.
start byte number to start your operation from. 0 is the first byte in the file, not 1.
newpos position in the file after a read or write has been performed. You'll need this if you're doing 'seeking' read/write.
size is the size of the objects you are trying to read. Rely on the values in the locale.inc file. Types are CHARACTER, INTEGER, REAL, COMPLEX. Specify the correct value by using SIZEOF_type, where type is one of these. (After having included the locale.inc file).
no is the number of things to read or write (characters, integers, whatever).
nactual is the number of things actually read or written. Check that you got what you wanted.
fdes is an integer 'file descriptor'. This is not a Fortran Unit Number You can use it, however, to refer to files you've previously opened.
fname is the name of the file. This only needs to be defined when you are opening a file. It must be (on the Fortran side) declared as CHARACTER*N, where N is a length greater than or equal to the length of the file name. CHARACTER*1 fname[80] (for example) will fail.
datary is the name of the entity (variable, vector, array) that you want to write data out from or read it in to. The fact that C is declaring it to be a char * does not affect your fortran.
namelen - Do NOT specify this. It is created automagically by the
Fortran compiler
datanamelen - Do NOT specify this. It is created automagically by the
Fortran compiler
Note
In your Fortran code, call bacio(), not bacio_().
What is going on here is that although the Fortran caller will always be calling bacio, the called C routine name will change from system to system.
Returns
0 All was well
255 Tried to open read only and write only
254 Tried to read and write in the same call
253 Internal failure in name processing
252 Failure in opening file
251 Tried to read on a write-only file
250 Failed in read to find the 'start' location
249 Tried to write to a read only file
248 Failed in write to find the 'start' location
247 Error in close
246 Read or wrote fewer data than requested
102 Massive catastrophe – datary pointer is NULL
Author
Robert Grumbine
Date
21 November 2008
< Read only.
< Write only.
< Write only truncate.
< Write only append.
< Read.
< Write.
< Read only.
< Write only.
< Write only truncate.
< Write only append.
< Read/write.
< Read only.
< Write only.
< Write only truncate.
< Write only append.
< Read/write.
< Read.
< Write only.
< Write only truncate.
< Write only append.
< Read.
< No seek.
< Write.
< Read only.
< Write.
< No seek.
< Close.
< Read only.
< Write only.
< Write only truncate.
< Write only append.
< Read/write.
< Read.
< Write.
Definition at line 817 of file bacio.c.
References bacio_module::baciol, BACLOSE, baniol_(), BAOPEN_RONLY, BAOPEN_RW, BAOPEN_WONLY, BAOPEN_WONLY_APPEND, BAOPEN_WONLY_TRUNC, BAREAD, BAWRITE, and NOSEEK.
Referenced by banio_().
banio_()
int banio_ (int * mode, int * start, int * newpos, int * size, int * no, int * nactual, int * fdes, const char * fname, char * datary, int namelen)
Do banio operation.
Parameters
mode integer specifying operations to be performed see the clib.inc file for the values. Mode is obtained by adding together the values corresponding to the operations The best method is to include the clib.inc file and refer to the names for the operations rather than rely on hard-coded values.
start byte number to start your operation from. 0 is the first byte in the file, not 1.
newpos position in the file after a read or write has been performed. You'll need this if you're doing 'seeking' read/write.
size is the size of the objects you are trying to read. Rely on the values in the locale.inc file. Types are CHARACTER, INTEGER, REAL, COMPLEX. Specify the correct value by using SIZEOF_type, where type is one of these. (After having included the locale.inc file).
no is the number of things to read or write (characters, integers, whatever).
nactual is the number of things actually read or written. Check that you got what you wanted.
fdes is an integer 'file descriptor'. This is not a Fortran Unit Number You can use it, however, to refer to files you've previously opened.
fname is the name of the file. This only needs to be defined when you are opening a file. It must be (on the Fortran side) declared as CHARACTER*N, where N is a length greater than or equal to the length of the file name. CHARACTER*1 fname[80] (for example) will fail.
datary is the name of the entity (variable, vector, array) that you want to write data out from or read it in to. The fact that C is declaring it to be a char * does not affect your fortran.
namelen - Do NOT specify this. It is created automagically by the
Fortran compiler
Note
In your Fortran code, call banio(), not banio_().
What is going on here is that although the Fortran caller will always be calling banio(), the called C routine name will change from system to system.
Returns
0 All was well
255 Tried to open read only and write only
254 Tried to read and write in the same call
253 Internal failure in name processing
252 Failure in opening file
251 Tried to read on a write-only file
250 Failed in read to find the 'start' location
249 Tried to write to a read only file
248 Failed in write to find the 'start' location
247 Error in close
246 Read or wrote fewer data than requested
102 Massive catastrophe – datary pointer is NULL
Author
Robert Grumbine
Date
16 March 1998
< Read only.
< Write only.
< Write only truncate.
< Write only append.
< Read.
< Write.
< Read only.
< Write only.
< Write only truncate.
< Write only append.
< Read/write.
< Read only.
< Write only.
< Write only truncate.
< Write only append.
< Read/write.
< Read.
< Write only.
< Write only truncate.
< Write only append.
< Read.
< No seek.
< Write.
< Read only.
< Write.
< No seek.
< Close.
< Read only.
< Write only.
< Write only truncate.
< Write only append.
< Read/write.
< Read.
< Write.
Definition at line 484 of file bacio.c.
References bacio_module::baciol, baciol_(), BACLOSE, BAOPEN_RONLY, BAOPEN_RW, BAOPEN_WONLY, BAOPEN_WONLY_APPEND, BAOPEN_WONLY_TRUNC, BAREAD, BAWRITE, and NOSEEK.
Referenced by bacio_().
baniol_()
int baniol_ (int * mode, long int * start, long int * newpos, int * size, long int * no, long int * nactual, int * fdes, const char * fname, char * datary, int namelen)
Do banio operation, with new names for long int arguments, needed for files > 2 Gb.
Parameters
mode integer specifying operations to be performed see the clib.inc file for the values. Mode is obtained by adding together the values corresponding to the operations The best method is to include the clib.inc file and refer to the names for the operations rather than rely on hard-coded values.
start byte number to start your operation from. 0 is the first byte in the file, not 1.
newpos position in the file after a read or write has been performed. You'll need this if you're doing 'seeking' read/write.
size is the size of the objects you are trying to read. Rely on the values in the locale.inc file. Types are CHARACTER, INTEGER, REAL, COMPLEX. Specify the correct value by using SIZEOF_type, where type is one of these. (After having included the locale.inc file).
no is the number of things to read or write (characters, integers, whatever).
nactual is the number of things actually read or written. Check that you got what you wanted.
fdes is an integer 'file descriptor'. This is not a Fortran Unit Number You can use it, however, to refer to files you've previously opened.
fname is the name of the file. This only needs to be defined when you are opening a file. It must be (on the Fortran side) declared as CHARACTER*N, where N is a length greater than or equal to the length of the file name. CHARACTER*1 fname[80] (for example) will fail.
datary is the name of the entity (variable, vector, array) that you want to write data out from or read it in to. The fact that C is declaring it to be a char * does not affect your fortran.
namelen - Do NOT specify this. It is created automagically by the
Fortran compiler
Note
In your Fortran code, call banio(), not banio_().
What is going on here is that although the Fortran caller will always be calling banio(), the called C routine name will change from system to system.
Returns
0 All was well
255 Tried to open read only and write only
254 Tried to read and write in the same call
253 Internal failure in name processing
252 Failure in opening file
251 Tried to read on a write-only file
250 Failed in read to find the 'start' location
249 Tried to write to a read only file
248 Failed in write to find the 'start' location
247 Error in close
246 Read or wrote fewer data than requested
102 Massive catastrophe – datary pointer is NULL
Author
Robert Grumbine
Date
16 March 1998
< Read only.
< Write only.
< Write only truncate.
< Write only append.
< Read.
< Write.
< Read only.
< Write only.
< Write only truncate.
< Write only append.
< Read/write.
< Read only.
< Write only.
< Write only truncate.
< Write only append.
< Read/write.
< Read.
< Write only.
< Write only truncate.
< Write only append.
< Read.
< No seek.
< Write.
< Read only.
< Write.
< No seek.
< Close.
< Read only.
< Write only.
< Write only truncate.
< Write only append.
< Read/write.
< Read.
< Write.
Definition at line 1171 of file bacio.c.
References BACLOSE, BAOPEN_RONLY, BAOPEN_RW, BAOPEN_WONLY, BAOPEN_WONLY_APPEND, BAOPEN_WONLY_TRUNC, BAREAD, BAWRITE, and NOSEEK.
Referenced by baciol_().