NCEPLIBS-bacio: byteswap.c File Reference
byteswap.c File Reference
This file contains various implementations of fast byteswapping routines.
#include <byteswap.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include "clib.h"
#include "fast-byteswap.h"
Macros
#define BLOCK_COUNT_16 (2048*1024)
Block Count 16.
#define BLOCK_COUNT_32 (1024*1024)
Block Count 32.
#define BLOCK_COUNT_64 (512*1024)
Block Count 64.
#define LINUX
Define LINUX.
Functions
static int block_macro_swap_16 (void *data, size_t len)
Use the GNU macros and do 1MB blocks at a time.
static int block_macro_swap_32 (void *data, size_t len)
Use the GNU macros and do 1MB blocks at a time.
static int block_macro_swap_64 (void *data, size_t len)
Use the GNU macros and do 1MB blocks at a time.
void byteswap_ (char *data, int *nbyte, int *nnum)
Byteswap.
int fast_byteswap (void *data, int bytes, size_t count)
Fast byteswap.
void fast_byteswap_errors (int flag)
Fast byteswap errors.
static int macro_swap_16 (void *data, size_t len)
Use the GNU macros, which are specialized byteswap ASM instructions.
static int macro_swap_32 (void *data, size_t len)
Use the GNU macros, which are specialized byteswap ASM instructions.
static int macro_swap_64 (void *data, size_t len)
Use the GNU macros, which are specialized byteswap ASM instructions.
static int simple_swap_16 (void *data, size_t len)
Simple single-value loops.
static int simple_swap_32 (void *data, size_t len)
Simple single-value loops.
static int simple_swap_64 (void *data, size_t len)
Simple single-value loops.
Variables
static int fast_count_calls = 0
Fast count calls.
static int send_errors = 1
if non-zero, warn about non-aligned pointers
Detailed Description
This file contains various implementations of fast byteswapping routines.
The main entry point, fast_byteswap(), is the only one you should need, and it should be modified to use whatever method is fastest on your architecture.
In all cases, the routines return 1 on success and 0 on failure. They only fail if your data is non-aligned. All routines require that arrays of N-bit data be N-bit aligned. If they are not, an error will be sent to stderr and the routine will return non-zero. To silence the error message, call fast_byteswap_errors(0).
Author
Dexin Zhang, Jun Wang
Definition in file byteswap.c.
Macro Definition Documentation
BLOCK_COUNT_16
#define BLOCK_COUNT_16 (2048*1024)
Block Count 16.
Definition at line 32 of file byteswap.c.
BLOCK_COUNT_32
#define BLOCK_COUNT_32 (1024*1024)
Block Count 32.
Definition at line 31 of file byteswap.c.
BLOCK_COUNT_64
#define BLOCK_COUNT_64 (512*1024)
Block Count 64.
Definition at line 30 of file byteswap.c.
LINUX
#define LINUX
Define LINUX.
Definition at line 33 of file byteswap.c.
Function Documentation
block_macro_swap_16()
static int block_macro_swap_16 (void * data, size_t len) static
Use the GNU macros and do 1MB blocks at a time.
Control the block size through the BLOCK_COUNT_* macros (top of file).
Parameters
data data
len Length
Returns
0 for error, 1 otherwise.
< Block Count 16.
< Block Count 16.
< Block Count 16.
< Block Count 16.
Definition at line 245 of file byteswap.c.
References BLOCK_COUNT_16, and send_errors.
block_macro_swap_32()
static int block_macro_swap_32 (void * data, size_t len) static
Use the GNU macros and do 1MB blocks at a time.
Control the block size through the BLOCK_COUNT_* macros (top of file).
Parameters
data data
len Length
Returns
0 for error, 1 otherwise.
< Block Count 32.
< Block Count 32.
< Block Count 32.
< Block Count 32.
Definition at line 216 of file byteswap.c.
References BLOCK_COUNT_32, and send_errors.
block_macro_swap_64()
static int block_macro_swap_64 (void * data, size_t len) static
Use the GNU macros and do 1MB blocks at a time.
Control the block size through the BLOCK_COUNT_* macros (top of file).
Parameters
data data
len Length
Returns
0 for error, 1 otherwise.
< Block Count 64.
< Block Count 64.
< Block Count 64.
< Block Count 64.
Definition at line 274 of file byteswap.c.
References BLOCK_COUNT_64, and send_errors.
byteswap_()
void byteswap_ (char * data, int * nbyte, int * nnum)
Byteswap.
Parameters
data Data
nbyte Number of bytes.
nnum NNUM
Definition at line 329 of file byteswap.c.
References fast_byteswap(), and fast_count_calls.
fast_byteswap()
int fast_byteswap (void * data, int bytes, size_t count)
Fast byteswap.
Parameters
data data
bytes Number of bytes
count Count.
Returns
0 for error, 1 otherwise.
Definition at line 303 of file byteswap.c.
References macro_swap_64(), simple_swap_16(), and simple_swap_32().
Referenced by byteswap_().
fast_byteswap_errors()
void fast_byteswap_errors (int flag)
Fast byteswap errors.
Parameters
flag flag
Definition at line 43 of file byteswap.c.
References send_errors.
macro_swap_16()
static int macro_swap_16 (void * data, size_t len) static
Use the GNU macros, which are specialized byteswap ASM instructions.
Parameters
data data
len Length
Returns
0 for error, 1 otherwise.
Definition at line 188 of file byteswap.c.
References send_errors.
macro_swap_32()
static int macro_swap_32 (void * data, size_t len) static
Use the GNU macros, which are specialized byteswap ASM instructions.
Parameters
data data
len Length
Returns
0 for error, 1 otherwise.
Definition at line 165 of file byteswap.c.
References send_errors.
macro_swap_64()
static int macro_swap_64 (void * data, size_t len) static
Use the GNU macros, which are specialized byteswap ASM instructions.
Parameters
data data
len Length
Returns
0 for error, 1 otherwise.
Definition at line 142 of file byteswap.c.
References send_errors.
Referenced by fast_byteswap().
simple_swap_16()
static int simple_swap_16 (void * data, size_t len) static
Simple single-value loops.
Parameters
data data
len Length
Returns
0 for error, 1 otherwise.
Definition at line 114 of file byteswap.c.
References send_errors.
Referenced by fast_byteswap().
simple_swap_32()
static int simple_swap_32 (void * data, size_t len) static
Simple single-value loops.
Parameters
data data
len Length
Returns
0 for error, 1 otherwise.
Definition at line 88 of file byteswap.c.
References send_errors.
Referenced by fast_byteswap().
simple_swap_64()
static int simple_swap_64 (void * data, size_t len) static
Simple single-value loops.
Parameters
data data
len Length
Returns
0 for error, 1 otherwise.
Definition at line 58 of file byteswap.c.
References send_errors.
Variable Documentation
fast_count_calls
int fast_count_calls = 0 static
Fast count calls.
Definition at line 36 of file byteswap.c.
Referenced by byteswap_().
send_errors
int send_errors = 1 static
if non-zero, warn about non-aligned pointers
Definition at line 35 of file byteswap.c.
Referenced by block_macro_swap_16(), block_macro_swap_32(), block_macro_swap_64(), fast_byteswap_errors(), macro_swap_16(), macro_swap_32(), macro_swap_64(), simple_swap_16(), simple_swap_32(), and simple_swap_64().