NCEPLIBS-bacio: chk_endianc.f90 File Reference
chk_endianc.f90 File Reference
Find endianness of files on a machine.
Functions/Subroutines
subroutine chk_endianc (mendian)
Obtain machine endianness.
subroutine findendian (mendian)
Obtain machine endianness.
Detailed Description
Find endianness of files on a machine.
Author
J. Wang
Date
Aug, 2012
Definition in file chk_endianc.f90.
Function/Subroutine Documentation
chk_endianc()
subroutine chk_endianc (character(16), intent(out) mendian)
Obtain machine endianness.
Parameters
mendian character(16) machine endianness
Author
J. Wang
Date
Aug, 2012
Definition at line 10 of file chk_endianc.f90.
References findendian().
Referenced by bafrindexl(), and bafrwritel().
findendian()
subroutine findendian (character(16), intent(out) mendian)
Obtain machine endianness.
Parameters
mendian character(16) machine endianness
Author
J. Wang
Date
Aug, 2012
Definition at line 27 of file chk_endianc.f90.
Referenced by chk_endianc().