NCEPLIBS-bacio: bacio_module Module Reference
bacio_module Module Reference
Byte-Addressable I/O Module.
Variables
integer, external bacio
BACIO.
integer, external baciol
BACIOL.
integer, dimension(20), save baopts =0
BAOPTS.
integer, dimension(fddim), save fd =FDDIM*0
FD.
integer, parameter fddim =9999
FDDIM.
Detailed Description
Byte-Addressable I/O Module.
This is a module to share file descriptors in the byte-addessable I/O package.
Author
Mark Iredell
Date
98-06-04
Variable Documentation
bacio
integer, external bacio_module::bacio
BACIO.
Definition at line 12 of file baciof.f90.
Referenced by bacio_().
baciol
integer, external bacio_module::baciol
BACIOL.
Definition at line 13 of file baciof.f90.
Referenced by baciol_(), baclose(), banio_(), baopen(), baopenr(), baopenw(), baopenwa(), baopenwt(), bareadl(), bawritel(), and wrytel().
baopts
integer, dimension(20), save bacio_module::baopts =0
BAOPTS.
Definition at line 16 of file baciof.f90.
Referenced by bareadl(), and baseto().
fd
integer, dimension(fddim), save bacio_module::fd =FDDIM*0
FD.
Definition at line 15 of file baciof.f90.
Referenced by baclose(), baopen(), baopenr(), baopenw(), baopenwa(), baopenwt(), bareadl(), bawritel(), and wrytel().
fddim
integer, parameter bacio_module::fddim =9999
FDDIM.
Definition at line 14 of file baciof.f90.
Referenced by baclose(), baopen(), baopenr(), baopenw(), baopenwa(), and baopenwt().