name: cdash
on:
  push: # make this 'push' for initial testing, then use 'merge'
    branches:
    - develop

jobs:
  cdash:
    runs-on: ubuntu-latest
    env:
      FC: gfortran
      CC: gcc
      CDASH_TOKEN: ${{ secrets.CDASH_TOKEN }}

    steps:

    - name: CDash
      uses: NOAA-EMC/ci-cdash@develop
