name: cdash
on:
  pull_request_target: # make this 'push' for initial testing, then use 'merge'
    branches:
    - develop

jobs:
  cdash:
    runs-on: ubuntu-latest

    steps:

    - name: CDash
      env:
        FC: gfortran
        CC: gcc
        CDASH_TOKEN: ${{ secrets.CDASH_TOKEN }}
      uses: NOAA-EMC/ci-cdash@develop
