name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      FC: gfortran-9
      CC: gcc-9

    steps:

    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install doxygen
        python3 -m pip install gcovr

    - name: checkout
      uses: actions/checkout@v2
      with: 
        path: bacio
        submodules: true

    - name: build
      run: |
        cd bacio
        mkdir build 
        cd build
        cmake .. -DENABLE_DOCS=ON -DCMAKE_Fortran_FLAGS="-g -fprofile-abs-path -fprofile-arcs -ftest-coverage -O0 -fsanitize=address"
        make -j2
    
    - name: test
      run: |
        cd $GITHUB_WORKSPACE/bacio/build
        ctest --version --output-on-error
        gcovr -r .. -v  --html-details -o test-coverage.html

    - name: upload-test-coverage
      uses: actions/upload-artifact@v2
      with:
        name: g2-test-coverage
        path: g2/build/*.html
        
